services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    volumes:
      - ./config:/config
      - /home/pietro/storage/downloads/complete:/downloads
      - /home/pietro/storage/tv:/tv
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    networks:
      - caddy-network

networks:
  caddy-network:
    external: true  #or comment this line to auto create the network


# /etc/fstab entry for directory storage
# /dev/sdb /home/pietro/storage ext4 defaults,user,rw 0 2