---
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD=password #optional
      - DEFAULT_WORKSPACE=/workspace #optional
    volumes:
      - ./config:/config
      - /home/pietro/homelab:/workspace
    ports:
      - 8443:8443
    restart: unless-stopped
