services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: caddy
    restart: unless-stopped
    env_file: .env
    ports:
      - 80:80
      - 443:443
#      - 2019:2019 #remove if you do not want admin API
    networks:
      - caddy-network
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data:rw
      - caddy-config:/config:rw
    environment:
      - CLOUDFLARE_EMAIL=${CF_EMAIL}
      - CLOUDFLARE_API_TOKEN=${CF_API_TOKEN}}
      - ACME_AGREE=true

volumes:
  caddy-data:
  caddy-config:

networks:
  caddy-network:
     external: true

# command to reload Caddy after making changes to Caddyfile
# > docker compose exec -w /etc/caddy caddy caddy reload