services:
  caddy:
    container_name: caddy
    image: docker.io/library/caddy:2-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data:rw
      - caddy-config:/config:rw
    # environment:
    #   - N8N_HOSTNAME=${N8N_HOSTNAME:-":8001"}
    #   - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL:-internal}
    # cap_drop:
    #   - ALL
    # cap_add:
    #   - NET_BIND_SERVICE
    # logging:
    #   driver: "json-file"
    #   options:
    #     max-size: "1m"
    #     max-file: "1"

volumes:
  caddy-data:
  caddy-config:

networks:
  caddy-network:
    # external: true

# command to reload Caddy after making changes to Caddyfile
# > docker compose exec -w /etc/caddy caddy caddy reload
