version: '2'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=Europe/London
      - PLEX_CLAIM=claim-xxxxxx
      - ADVERTISE_IP=http://server.ip.address:32400/
      - PLEX_UID=1000 # might need to change this
      - PLEX_GID=1000 # might need to change this
    hostname: plexserver.example.com
    volumes:
      - /home/folder/services/plex/database:/config
      - /home/folder/services/plex/transcode:/transcode
      - /home/folder/services/plex/media:/data
    networks:
      - proxy

networks:
  proxy:
    external: true