version: '3.7'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=Europe/London
      - PLEX_CLAIM=claim-1Ya8dRpdYn8Bh4a4xsQy
      - ADVERTISE_IP=http://192.168.10.100:32400/
      - PLEX_UID=1000
      - PLEX_GID=1000
      - HOSTNAME=DockerPlexServer
    hostname: plexserver.unifyhubs.com
    volumes:
      - /home/pietro/services/plex/database:/config
      - /home/pietro/services/plex/transcode:/transcode
      - /home/pietro/media:/data

# You need to use the Plex Claim in order to add this server to your plex account. 
# The procedure for getting the actual token you need is as follows
# Visit https://www.plex.tv/claim/