version: '2'
services:
  # plex:
  #   container_name: plex
  #   image: plexinc/pms-docker
  #   restart: unless-stopped
  #   # ports:
  #   #   - 32400:32400/tcp #web ui port
  #   #   - 3005:3005/tcp
  #   #   - 8324:8324/tcp
  #   #   - 32469:32469/tcp
  #   #   - 1900:1900/udp
  #   #   - 32410:32410/udp
  #   #   - 32412:32412/udp
  #   #   - 32413:32413/udp
  #   #   - 32414:32414/udp
  #   environment:
  #     - TZ=Europe/London
  #     - PLEX_CLAIM=claim-xxxxxx
  #     - PLEX_UID=1000
  #     - PLEX_GID=1000
  #     - HOSTNAME=PlexMediaServer
  #   volumes:
  #     - ./plex/database:/config
  #     - ./plex/transcode:/transcode
  #     - /home/pietro/media/movies:/movies
  #     - /home/pietro/media/tv:/tv
  #   networks:
  #     - proxy
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.protocol=https"
  #     - "traefik.http.routers.plex.entrypoints=http"
  #     - "traefik.http.routers.plex.rule=Host(`plex.unifyhubs.com`)"
  #     - "traefik.http.middlewares.plex-https-redirect.redirectscheme.scheme=https"
  #     - "traefik.http.routers.plex.middlewares=plex-https-redirect"
  #     - "traefik.http.routers.plex-secure.entrypoints=https"
  #     - "traefik.http.routers.plex-secure.rule=Host(`plex.unifyhubs.com`)"
  #     - "traefik.http.routers.plex-secure.tls=true"
  #     - "traefik.http.routers.plex-secure.service=plex"
  #     - "traefik.http.services.plex.loadbalancer.server.port=32400"
  #     - "traefik.docker.network=proxy"

  # # # more info here -->  https://github.com/plexinc/pms-docker
  # # # You need to use the Plex Claim in order to add this server to your plex account. 
  # # # The procedure for getting the actual token you need is as follows
  # # # Visit https://www.plex.tv/claim/

  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./nzbget/config:/config
      - ./nzbget/downloads:/downloads
      - /home/pietro/media/intermediate:/intermediate
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nzbget.entrypoints=http"
      - "traefik.http.routers.nzbget.rule=Host(`nzbget.unifyhubs.com`)"
      - "traefik.http.middlewares.nzbget-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.nzbget.middlewares=nzbget-https-redirect"
      - "traefik.http.routers.nzbget-secure.entrypoints=https"
      - "traefik.http.routers.nzbget-secure.rule=Host(`nzbget.unifyhubs.com`)"
      - "traefik.http.routers.nzbget-secure.tls=true"
      - "traefik.http.routers.nzbget-secure.service=nzbget"
      - "traefik.http.services.nzbget.loadbalancer.server.port=6789"
      - "traefik.docker.network=proxy"
 
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    depends_on:
        - nzbget
    volumes:
      - ./sonarr/config:/config
      - ./nzbget/downloads:/downloads
      - /home/pietro/media/tv:/tv
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.entrypoints=http"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.unifyhubs.com`)"
      - "traefik.http.middlewares.sonarr-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.sonarr.middlewares=sonarr-https-redirect"
      - "traefik.http.routers.sonarr-secure.entrypoints=https"
      - "traefik.http.routers.sonarr-secure.rule=Host(`sonarr.unifyhubs.com`)"
      - "traefik.http.routers.sonarr-secure.tls=true"
      - "traefik.http.routers.sonarr-secure.service=sonarr"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
      - "traefik.docker.network=proxy"
  
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    depends_on:
      - nzbget
    volumes:
      - ./radarr/config:/config
      - ./nzbget/downloads:/downloads
      - /home/pietro/media/movies:/movies
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.entrypoints=http"
      - "traefik.http.routers.radarr.rule=Host(`radarr.unifyhubs.com`)"
      - "traefik.http.middlewares.radarr-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.radarr.middlewares=radarr-https-redirect"
      - "traefik.http.routers.radarr-secure.entrypoints=https"
      - "traefik.http.routers.radarr-secure.rule=Host(`radarr.unifyhubs.com`)"
      - "traefik.http.routers.radarr-secure.tls=true"
      - "traefik.http.routers.radarr-secure.service=radarr"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
      - "traefik.docker.network=proxy"

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    networks:
      - proxy
    volumes:
      - ./jellyfin/library:/config
      - /home/pietro/media/movies:/movies
      - /home/pietro/media/tv:/tvshows
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.entrypoints=http"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.unifyhubs.com`)"
      - "traefik.http.middlewares.jellyfin-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.jellyfin.middlewares=jellyfin-https-redirect"
      - "traefik.http.routers.jellyfin-secure.entrypoints=https"
      - "traefik.http.routers.jellyfin-secure.rule=Host(`jellyfin.unifyhubs.com`)"
      - "traefik.http.routers.jellyfin-secure.tls=true"
      - "traefik.http.routers.jellyfin-secure.service=jellyfin"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true