---
version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000 # this might change
      - PGID=1000 # this might change
      - TZ=Europe/London
    volumes:
      - /home/user/services/radarr/data:/config
      #- /path/to/movies:/movies #optional
      #- /path/to/downloadclient-downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true