services: 
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    volumes:
      - ./config:/config
      - /home/pietro/storage/downloads/complete:/downloads
      - /home/pietro/storage/media/movies:/movies
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - 7878:7878
    networks:
      - caddy-network

networks:
  caddy-network:
    external: true  #or comment this line to auto create the network
    