services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    devices:
      # VAAPI Devices
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    group_add: # by id as these may not exist within the container. Needed to provide permissions to the VAAPI Devices
      - '993' # render
    volumes:
      - ./jellyfin/library:/config
      - /home/pietro/storage/movies:/movies
      - /home/pietro/storage/tv:/tvshows
    networks:
      - caddy-network

networks:
  caddy-network:
    external: true  #or comment this line to auto create the network