version: '3.3'

volumes:
  uptimekuma:

services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    volumes:
      - ./:/app/data
    ports:
      - 3001:3001
    restart: unless-stopped
