services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: syncthing-docker
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/pietro/storage/syncthing:/var/syncthing
    ports:
      - 8384:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    restart: unless-stopped

# /etc/fstab entry for directory storage
# /dev/sdb /home/pietro/storage ext4 defaults,user,rw 0 2