services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./config:/config
      - /home/pietro/storage/media/downloads/complete:/downloads #optional
      - /home/pietro/storage/media/downloads/incomplete:/incomplete-downloads #optional
    ports:
      - 8080:8080
    restart: unless-stopped
    networks:
      - caddy-network

networks:
  caddy-network:
    external: true  #or comment this line to auto create the network
